### ISSUE TITLE
Decouple count from query in results workflow

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/serrano#254]
The first page of results should be returned and displayed independently of the results count being displayed.

**Comment by bruth** [comment]
In order for this to work, the pagination components will need to be removed since the number of pages and thus the links require the count to be computed. However the resource still needs to receive the `page` and `limit` request params so it can calculate the `OFFSET` (so the right page is returned).

This unfortunately prevents the ability to create the page links since the size of the result set is unknown. However, there could be a parameter to invoke retrieving a *fast* page of results.
